name: Deploy CI
run-name: ${{ github.run_id }} in ${{ github.workflow }} deploying
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Check Format code
              run: npm run format:check
            - name: Run tests
              run: npm run test:ci
            - name: Run Build
              run: npm run build:rollup
            - name: Copy package.json, README.md, LICENSE to dist
              run: |
                  cp package.json dist/package.json
                  cp README.md dist/README.md
                  cp LICENSE dist/LICENSE
            - name: Generate Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist ${{ github.run_id }}
                  path: dist
